name: AngularBulma
description: Bulma css with 22 custom templates :)
version: 0.7.1
#homepage: https://www.example.com
#author: SpivEgin <email@example.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

#dependencies:

#dev_dependencies:
#  test: ^0.12.0
